name: neuro_conecta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  file_picker: ^8.0.0      
  url_launcher: ^6.2.5    
  image_picker: ^1.0.7
  video_player: ^2.8.2
  chewie: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/neuro_conecta_icono.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/neuro_conecta_logo.png
    - assets/images/neuro_conecta_logo1.png
    - assets/images/neuro_conecta_logo2.png
    - assets/images/neuro_conecta_icono.png