name: neuro_conecta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  video_player: ^2.8.2
  chewie: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Herramienta para generar los iconos del lanzador automáticamente.
  flutter_launcher_icons: ^0.13.1

# Configuración del Icono de la App (Launcher)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/neuro_conecta_logo.png" # Nombre del archivo corregido.
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  # Registro de Assets para que la app pueda usarlos.
  assets:
    - assets/images/neuro_conecta_logo.png
    - assets/images/neuro_conecta_logo1.png